#!/bin/sh

ENABLED=yes
PROCS=qbittorrent-nox
ARGS="--webui-port=9080 --profile=/opt/etc --configuration=entware -d"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


. /opt/etc/init.d/rc.func
