/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Wed Dec  9 12:16:59 2015"
#define BUILD_TIME (1449663419L)

#define VERSION_NUMBER 0x03060002UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c617eUL
#define VERSION_SANITY2 0xf48195c4UL
#define VERSION_SANITY3 0x00025000UL

#define VERSION_STRING "3.6.0"
#define VERSION_ID \
 "Unix NetHack Version 3.6.0 - last build Wed Dec  9 12:16:59 2015."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.0 Unix, built Dec  9 12:16:59 2015."
