#!/bin/sh

ENABLED=yes
PROCS=ympd
ARGS="-w 8800 -h localhost -p 6600"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
