#!/bin/sh

ENABLED=yes
PROCS=3proxy
ARGS="/opt/etc/3proxy/3proxy.cfg"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
