#!/bin/sh

ENABLED=yes
PROCS=ps3netsrv
ARGS="/opt/share/ps3netsrv"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
