#!/bin/sh

ENABLED=yes
PROCS=Pcap_DNSProxy
ARGS="--config-file /opt/etc/pcap-dnsproxy"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
