#!/bin/sh

HOME="/opt/var/lib"
mkdir -p $HOME/.i2pd/addressbook/etags

ENABLED=yes
PROCS=i2pd
ARGS="--conf=/opt/etc/i2p.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
