#!/bin/sh

ENABLED=yes
PROCS=PtokaX
ARGS="-d -c /opt/share/ptokax/"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
