#!/bin/sh

ENABLED=yes
PROCS=msd
ARGS="-d -c /opt/etc/msd.conf -p /opt/var/run/msd.pid"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
