#!/bin/sh

ENABLED=yes
PROCS=shellinaboxd
ARGS="-t -u root --css /opt/lib/shellinabox/white-on-black.css -b"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
